### ISSUE TITLE
Can't connect (404 Not Found?)

### ISSUE THREAD

**Issue by yunikuneko** [pimusicbox/mopidy-websettings#26]
Hey there,

I'm running Mopidy on a Ubuntu Desktop 17.10 system which has the IP of 10.0.0.211 on my local network... when I visit http://10.0.0.211:6680/settings... It just spews out `404: Not Found`. I've tried running `$ pip install Mopidy-WebSettings` as both my local user and as root and had no luck in it showing up. Latest log of pip install is: 
```
$ pip install Mopidy-WebSettings
Collecting Mopidy-WebSettings
  Downloading Mopidy_WebSettings-0.2.0-py2.py3-none-any.whl
Collecting Jinja2>=2.7 (from Mopidy-WebSettings)
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 1.6MB/s 
Collecting ConfigObj>=4.0.0 (from Mopidy-WebSettings)
  Downloading configobj-5.0.6.tar.gz
Requirement already satisfied: Mopidy>=0.19 in /usr/lib/python2.7/dist-packages (from Mopidy-WebSettings)
Requirement already satisfied: Pykka>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy-WebSettings)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from Mopidy-WebSettings)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7->Mopidy-WebSettings)
  Downloading MarkupSafe-1.0.tar.gz
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from ConfigObj>=4.0.0->Mopidy-WebSettings)
Building wheels for collected packages: ConfigObj, MarkupSafe
  Running setup.py bdist_wheel for ConfigObj ... done
  Stored in directory: /root/.cache/pip/wheels/87/76/48/1564f8466fbd36402af5ac4972ffb56a6ef7f143892ef57fe5
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built ConfigObj MarkupSafe
Installing collected packages: MarkupSafe, Jinja2, ConfigObj, Mopidy-WebSettings
Successfully installed ConfigObj-5.0.6 Jinja2-2.10 MarkupSafe-1.0 Mopidy-WebSettings-0.2.0
```
And Mopidy log is:
```
2017-11-10 15:42:31,690 INFO [676:MainThread] mopidy.__main__: Starting Mopidy 2.1.0
2017-11-10 15:42:32,449 INFO [676:MainThread] mopidy.config: Loading config from builtin defaults
2017-11-10 15:42:32,486 INFO [676:MainThread] mopidy.config: Loading config from /etc/mopidy/mopidy.conf
2017-11-10 15:42:32,529 INFO [676:MainThread] mopidy.config: Loading config from command line options
2017-11-10 15:42:33,854 INFO [676:MainThread] mopidy.__main__: Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer, file, local
2017-11-10 15:42:33,854 INFO [676:MainThread] mopidy.__main__: Disabled extensions: none
2017-11-10 15:42:37,259 INFO [676:MainThread] mopidy.commands: Starting Mopidy mixer: SoftwareMixer
2017-11-10 15:42:37,260 INFO [676:MainThread] mopidy.commands: Starting Mopidy audio
2017-11-10 15:42:37,261 INFO [676:MainThread] mopidy.commands: Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend, SpotifyBackend
2017-11-10 15:42:37,303 INFO [676:MainThread] mopidy.local.json: No local library metadata cache found at /var/lib/mopidy/local/library.json.gz. Please run `mopidy local scan` to$
2017-11-10 15:42:37,303 INFO [676:MainThread] mopidy.local.library: Loaded 0 local tracks using json
2017-11-10 15:42:37,330 INFO [676:Audio-2] mopidy.audio.actor: Audio output set to "autoaudiosink"
2017-11-10 15:42:37,526 INFO [676:MainThread] mopidy.commands: Starting Mopidy core
2017-11-10 15:42:37,588 INFO [676:SpotifyEventLoop] spotify.session: Spotify logged in
2017-11-10 15:42:37,589 INFO [676:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in offline mode
2017-11-10 15:42:38,111 INFO [676:MainThread] mopidy.commands: Starting Mopidy frontends: MpdFrontend, HttpFrontend
2017-11-10 15:42:38,112 INFO [676:MainThread] mopidy.mpd.actor: MPD server running at [::ffff:127.0.0.1]:6600
2017-11-10 15:42:38,115 INFO [676:MainThread] mopidy.commands: Starting GLib mainloop
2017-11-10 15:42:38,116 INFO [676:HttpFrontend-14] mopidy.http.actor: HTTP server running at [::ffff:10.0.0.211]:6680
2017-11-10 15:42:38,366 INFO [676:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2017-11-10 15:50:51,393 WARNING [676:HttpServer] tornado.access: 404 GET /settings (10.0.0.210) 0.36ms
2017-11-10 15:50:51,795 WARNING [676:HttpServer] tornado.access: 404 GET /settings/ (10.0.0.210) 0.34ms
2017-11-10 15:50:55,177 WARNING [676:HttpServer] tornado.access: 404 GET /settings (10.0.0.210) 0.35ms
```
Hoping you have any idea of whats going wrong?..

**Comment by yunikuneko** [comment]
just tried `$ sudo mopidyctl local scan` and still no luck >.<

**Comment by daverck** [comment]
I think it's only accessible from localhost by default.

**Comment by gmkey** [comment]
I'm getting this error message, which makes no sense to me.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_websettings/__init__.py", line 96, in get
    configValue = iniconfig.get(item, {}).get(subitem, None)
UnboundLocalError: local variable 'iniconfig' referenced before assignment
```

**Comment by kingosticks** [comment]
@gmkey I've moved this to a new issue since it's not obvious to me your report is the same as this old issue (which is possibly about wrong configuration, I don't know).
