### ISSUE TITLE
Can't load config file on FreeNas jail

### ISSUE THREAD

**Issue by TheOnlyMunk** [pimusicbox/mopidy-websettings#34]
Installed mopidy in a freenas jail. Trying to set up websettings but on launch it can't find my config located here:

~/.config/mopidy/mopidy.conf

**Comment by kingosticks** [comment]
Did you

> Make sure the config file is writable by the user under which mopidy is running

?

**Comment by sphh** [comment]
Looks like I have the same or similar problem:

- I use the system-wide configuration file `/etc/mopidy/mopidy.conf`.
- `mopidy` runs under the user `mopidy`.
- The system-wide configuration file is owned by `mopidy` and is writeable.

I believe I did everything right, but apparently I did not.

**`/etc/mopidy/mopidy.conf`**:
```ini
[websettings]
# https://pypi.org/project/Mopidy-WebSettings/
enabled = true
musicbox = false
config_file = /etc/mopidy/mopidy.conf
```

**`$ ps aux | grep mopidy`**:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mopidy    1101 17.1 11.3 259812 55848 ?        Ssl  11:03   2:32 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf
```

**Permissions**:
```sh
$ ls -ld /etc/mopidy
drwxr-xr-x 2 mopidy root 4096 Jun 11 13:46 /etc/mopidy
$ ls -l /etc/mopidy
total 8
-rw-r----- 1 mopidy root 802 Jun 25 10:59 mopidy.conf
```

**`$ sudo journalctl -u mopidy`**:
```log
Jun 25 11:03:20 mopidy mopidy[1101]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Jun 25 11:03:20 mopidy mopidy[1101]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Jun 25 11:03:20 mopidy mopidy[1101]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Jun 25 11:03:20 mopidy mopidy[1101]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Jun 25 11:03:20 mopidy mopidy[1101]: INFO     [MainThread] mopidy.config Loading config from command line options
Jun 25 11:03:25 mopidy mopidy[1101]: INFO     [MainThread] mopidy.__main__ Enabled extensions: websettings, softwaremixer, cd, m3u, file, stream, musicbox_webclie
Jun 25 11:03:25 mopidy mopidy[1101]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Jun 25 11:03:27 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Jun 25 11:03:27 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Jun 25 11:03:27 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: ORFBackend, CdBackend, FileBackend, M3UBackend, StreamBackend
Jun 25 11:03:27 mopidy mopidy[1101]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "autoaudiosink"
Jun 25 11:03:28 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Jun 25 11:03:28 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend
Jun 25 11:03:28 mopidy mopidy[1101]: INFO     [HttpFrontend-10] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Jun 25 11:03:28 mopidy mopidy[1101]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Jun 25 11:03:59 mopidy mopidy[1101]: ERROR    [HttpServer] mopidy_websettings Could not load ini file! Parsing failed with several errors.
Jun 25 11:03:59 mopidy mopidy[1101]: First error at line 27.
Jun 25 11:03:59 mopidy mopidy[1101]: ERROR    [HttpServer] tornado.application Uncaught exception GET /settings/ (192.168.8.100)
Jun 25 11:03:59 mopidy mopidy[1101]: HTTPServerRequest(protocol='http', host='192.168.8.21:6680', method='GET', uri='/settings/', version='HTTP/1.1', remote_ip='1
Jun 25 11:03:59 mopidy mopidy[1101]: Traceback (most recent call last):
Jun 25 11:03:59 mopidy mopidy[1101]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
Jun 25 11:03:59 mopidy mopidy[1101]:     result = method(*self.path_args, **self.path_kwargs)
Jun 25 11:03:59 mopidy mopidy[1101]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_websettings/__init__.py", line 95, in get
Jun 25 11:03:59 mopidy mopidy[1101]:     configValue = iniconfig.get(item, {}).get(subitem, None)
Jun 25 11:03:59 mopidy mopidy[1101]: UnboundLocalError: local variable 'iniconfig' referenced before assignment
Jun 25 11:03:59 mopidy mopidy[1101]: ERROR    [HttpServer] tornado.access 500 GET /settings/ (192.168.8.100) 2918.18ms
```

**`$ systemctl status mopidy`**:
```
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-06-25 10:59:35 CEST; 57s ago
  Process: 1012 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 1013 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 1014 (mopidy)
   Memory: 29.6M
   CGroup: /system.slice/mopidy.service
           └─1014 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Jun 25 11:00:25 mopidy mopidy[1014]: First error at line 27.
Jun 25 11:00:26 mopidy mopidy[1014]: ERROR    [HttpServer] tornado.application Uncaught exception GET /settings/ (192.168.8.100)
Jun 25 11:00:26 mopidy mopidy[1014]: HTTPServerRequest(protocol='http', host='192.168.8.21:6680', method='GET', uri='/settings/', version='HTTP/1.1', remote_ip='1
Jun 25 11:00:26 mopidy mopidy[1014]: Traceback (most recent call last):
Jun 25 11:00:26 mopidy mopidy[1014]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
Jun 25 11:00:26 mopidy mopidy[1014]:     result = method(*self.path_args, **self.path_kwargs)
Jun 25 11:00:26 mopidy mopidy[1014]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_websettings/__init__.py", line 95, in get
Jun 25 11:00:26 mopidy mopidy[1014]:     configValue = iniconfig.get(item, {}).get(subitem, None)
Jun 25 11:00:26 mopidy mopidy[1014]: UnboundLocalError: local variable 'iniconfig' referenced before assignment
Jun 25 11:00:26 mopidy mopidy[1014]: ERROR    [HttpServer] tornado.access 500 GET /settings/ (192.168.8.100) 4716.84ms
```

**Comment by sphh** [comment]
Please disregard my last post (which I just deleted). I found the problem, it is Bug 29. It might help to give a more descriptive error message, such as
```
ERROR    [HttpServer] mopidy_websettings Could not load ini file! Parsing failed with several errors.
First error at line 27 in file /etc/mopidy/mopidy.conf.
```
